#!/usr/bin/env python3
# pip3 install pyvisa
# pip3 install pyvisa-py

import pyvisa
from pyvisa import constants
import argparse

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('device',
                        help='Serial port the scope is attached to')
    parser.add_argument('file',
                        help='File to write the output to')

    global args
    args = parser.parse_args()

    if not args.file.endswith('.bmp'):
        args.file = args.file + '.bmp'

    rm = pyvisa.ResourceManager()

    instr = rm.open_resource(f'ASRL{args.device}::INSTR', baud_rate=57600,
        flow_control=constants.VI_ASRL_FLOW_DTR_DSR,
        write_termination = '\n', read_termination='\n',
        timeout=45000)

    res = instr.query_binary_values(":DISPlay:DATA? BMP",
        datatype='B', container=bytearray)

    with open(args.file, "wb") as f:
        f.write(res)

    print("Screen image written to {}".format(args.file))

    rm.close()

if __name__ == '__main__':
    main()
